### ISSUE TITLE
大神有问题请教

### ISSUE THREAD

**Issue by javaeryang** [zhudongya123/WechatChatroomHelper#1]
大神可否研究下,消息长按**弹出菜单**,和对它设置**监听器**,目前我实现了添加菜单选项,但是没法设置监听器,求大神看看能否解决?**com.tencent.mm.ui.chatting.En_5b8fbb1e**微信**6.5.10**版,里面有个**a**静态内部类,**a**里有个构造方法,里面就是添加contextMenu的操作,求大神能看看怎么设置监听器

**Comment by zhudongya123** [comment]
会注意的，目前也在看这方面的内容。

**Comment by javaeryang** [comment]
我是用jadx-0.61版本,

**Comment by renfengrain** [comment]
大神能不能把微信公众号消息也归类下！？

**Comment by javaeryang** [comment]
@zhudongya123 不知大神有没有看? 我想问一下大神,xsharepreference读取不到数据好像,总是会返回默认的值,比如boolean类型,返回默认的false,但是实际并不是false,而是true的,

**Comment by javaeryang** [comment]
![_20170827000139](https://user-images.githubusercontent.com/27242250/29742989-606cafe0-8abb-11e7-9ba6-80cb5191a733.png)

**Comment by javaeryang** [comment]
![_20170827000419](https://user-images.githubusercontent.com/27242250/29742997-742982e2-8abb-11e7-85c7-76de5f3d42b3.png)

**Comment by javaeryang** [comment]
图2中的log始终打印false,即使shareprefs文件里是true

**Comment by zhudongya123** [comment]
@javaeryang 

- 因为我还在弄我readme里面的bug，长按菜单目前还没有研究。

- 首先确定你的PreferenceUtil所在的包是不是和你的应用程序的包名完全相同。

- 然后确定你在你的应用程序里面读写SharePreference时，使用的文件名是什么？ XSharedPreferences 默认传入的 String 是与应用程序种 PreferenceFragment 的默认文件一致，文件名为 package+_prefreences。所以你可以找一台 root 过的手机进入 data/data/包名/shared_prefreences 文件夹中查看是否一致。

**Comment by zhudongya123** [comment]
@renfengrain 在全部修正完本程序基本功能的问题之前，暂时没有这方面的考虑。

**Comment by renfengrain** [comment]
好的！6.5.13开始适配了么？大神！

**Comment by zhudongya123** [comment]
@renfengrain 已经适配了。

**Comment by renfengrain** [comment]
好的！谢谢！及时效率高！

**Comment by javaeryang** [comment]
感谢大神的解答,修改为正确包名后,正确读取,

**Comment by zhudongya123** [comment]
#

**Comment by jayjd** [comment]
@zhudongya123 借此贴问下大神 
android7 限制了MODE_WORLD_READABLE的使用
XSharedPreferences怎么读取SharedPreferences保存的数据啊?
再次感谢!!

**Comment by zhudongya123** [comment]
@jayjd MODE_WORLD_READABLE不影响吧 XSharedPreferences的makeworldreadable不就可以了么

**Comment by jayjd** [comment]
@zhudongya123  测试过了 在包名的目录下 还是没有权限读取
我用其他方式实现了
