### ISSUE TITLE
给大神的建议

### ISSUE THREAD

**Issue by javaeryang** [zhudongya123/WechatChatroomHelper#10]
自从大神开源以来，衍生出多种版本[仅猜测]，比如（群聊归拢，微信分组......）
在此提个假设吧，
如果作者把群聊转移到微信通讯录，
把其中一项作为入口，把部分好友移动过去，
再把入口隐藏，添加个开关，是不是就成为‘密友功能’了
以上纯属建议，胡说八道，不足挂齿，仅供参考，[手动滑稽]

**Comment by zhudongya123** [comment]
不要叫我大神了。。。整个issue里面全是大神大神。。。。
