### ISSUE TITLE
时隔一年多了，再次想请问大神一个问题

### ISSUE THREAD

**Issue by javaeryang** [zhudongya123/WechatChatRoomHelper#14]
我克隆了大神的项目，尝试去看代码，不过没看懂，如何实现的。
1、微信聊天界面的ListView,如何把自己已经归拢的群聊，隐藏掉。
2、看了大神hook了ListView的getView方法，以及getCount等方法，却没看懂其逻辑。
大神有空麻烦给我说说其原理？以及你的代码逻辑。
ListView的item项点击事件之后的逻辑基本理解。

**Comment by zhudongya123** [comment]
我后期应该会注意一下更加整理代码出个文档，应该就在这一两个月，你可以关注一下，加微信 helper_2017 我有个反馈群可以了解。

**Comment by javaeryang** [comment]
> 我后期应该会注意一下更加整理代码出个文档，应该就在这一两个月，你可以关注一下，加微信 helper_2017 我有个反馈群可以了解。

已经添加了大神微信，有空通过下，ID是Javaer

**Comment by javaeryang** [comment]
多谢大神整理文档。

**Comment by zhudongya123** [comment]
https://github.com/zhudongya123/WechatChatRoomHelper_Tutorial 
仓库已经建立 慢慢更新
