### ISSUE TITLE
无反应

### ISSUE THREAD

**Issue by Goku0902** [zhudongya123/WechatChatRoomHelper#19]
微信7.0.4，群消息助手1.4.4无效果

**Comment by Goku0902** [comment]
用普通太极

**Comment by zhudongya123** [comment]
用1.4.5试试看

**Comment by Goku0902** [comment]
在哪下载？酷安没有了
发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Mr.Zdy <notifications@github.com>
发送时间: Friday, July 5, 2019 10:59:02 AM
收件人: zhudongya123/WechatChatRoomHelper
抄送: Goku0902; Author
主题: Re: [zhudongya123/WechatChatRoomHelper] 无反应 (#19)


用1.4.5试试看

―

**Comment by zhudongya123** [comment]
xposed仓库看看
