### ISSUE TITLE
 群聊消息和服务号消息都打不开，闪一下就没了

### ISSUE THREAD

**Issue by NigelSong** [zhudongya123/WechatChatRoomHelper#30]
安卓9，无极框架，微信7.0.9 Play版，群消息助手1.4.5，消息界面点击“群聊管理”或“订阅号管理”，界面只是闪烁了一下，没有打开归拢界面。

**Comment by NigelSong** [comment]
微信是64位的

**Comment by zhudongya123** [comment]
记录了，待解决

**Comment by zhudongya123** [comment]
已经好了 到这里下载版本 http://122.152.202.233:8080/wechat/wechat_download.jsp
