### ISSUE TITLE
如果作者可以适配微信的暗黑模式，就好了

### ISSUE THREAD

**Issue by NigelSong** [zhudongya123/WechatChatRoomHelper#34]
如果可以把这个UI改成灰色的，哪怕提供一个手动设置的入口，我觉得效果会更好。
![Screenshot_20200218-184505 (1)](https://user-images.githubusercontent.com/23294384/74729623-b3dab300-527f-11ea-933e-aff3350dbad4.jpg)

**Comment by lllinusss** [comment]
你啥版本的微信？啥系统？居然还能用？

**Comment by NigelSong** [comment]
#32 把“上帝模式”关了就能用了，或者试试“设置生效范围”里把微信排除掉（太极6.0.0以后有此功能）

**Comment by zhudongya123** [comment]
等到微信把这个release了我在做吧
