### ISSUE TITLE
在微信7.0.12中突然就失效了

### ISSUE THREAD

**Issue by KiWinger** [zhudongya123/WechatChatRoomHelper#36]
RT，本来更新后还有效的，昨晚上突然就失效了
没做什么，强停，清数据，删文件夹，重新匹配，重装都无法恢复😳
重启也无效

**Comment by zhudongya123** [comment]
太极还是Edxp，edxp日志有看下？

**Comment by KiWinger** [comment]
[EdXposed_Verbose_20200314_231703.log](https://github.com/zhudongya123/WechatChatRoomHelper/files/4332940/EdXposed_Verbose_20200314_231703.log)
详细日志

**Comment by KiWinger** [comment]
[error.log](https://github.com/zhudongya123/WechatChatRoomHelper/files/4357743/error.log)
最近最新的一次模块日志，在最下面底部，刚刚尝试清除一系列操作的日志

**Comment by lllinusss** [comment]
你用的那个版本啊？github上的1.4.5我老早就不能用了

**Comment by KiWinger** [comment]
的确，1.4.5，我居然还能用一段时间😂请问现在有能用的版本吗？

**Comment by zhudongya123** [comment]
> [error.log](https://github.com/zhudongya123/WechatChatRoomHelper/files/4357743/error.log)
> 最近最新的一次模块日志，在最下面底部，刚刚尝试清除一系列操作的日志

比较尴尬 你这个日志里面还是没有关于我模块的任何错误日志。

现在的确有用户报告忽然失效，但是本身没有什么问题，你们可以尝试反复重新安装，重启，卸载来多尝试几遍，一遍不行，多来几遍。

**Comment by KiWinger** [comment]
行的👌多谢

**Comment by lllinusss** [comment]
> > [error.log](https://github.com/zhudongya123/WechatChatRoomHelper/files/4357743/error.log)
> > 最近最新的一次模块日志，在最下面底部，刚刚尝试清除一系列操作的日志
> 
> 比较尴尬 你这个日志里面还是没有关于我模块的任何错误日志。
> 
> 现在的确有用户报告忽然失效，但是本身没有什么问题，你们可以尝试反复重新安装，重启，卸载来多尝试几遍，一遍不行，多来几遍。

请问下现在最新的是146吗？找不到在哪下啊，github上只有145

**Comment by KiWinger** [comment]
> > > [error.log](https://github.com/zhudongya123/WechatChatRoomHelper/files/4357743/error.log)
> > > 最近最新的一次模块日志，在最下面底部，刚刚尝试清除一系列操作的日志
> > 
> > 
> > 比较尴尬 你这个日志里面还是没有关于我模块的任何错误日志。
> > 现在的确有用户报告忽然失效，但是本身没有什么问题，你们可以尝试反复重新安装，重启，卸载来多尝试几遍，一遍不行，多来几遍。
> 
> 请问下现在最新的是146吗？找不到在哪下啊，github上只有145

http://122.152.202.233:8080/wechat/wechat_download.jsp
