### ISSUE TITLE
如果不在群消息助手里,想最快打开消息助手,加入这个菜单是不是体验更好

### ISSUE THREAD

**Issue by javaeryang** [zhudongya123/WechatChatroomHelper#4]
![j](https://user-images.githubusercontent.com/27242250/30251312-d0c3bc04-968f-11e7-9b5a-db4c128585e4.png)

**Comment by zhudongya123** [comment]
但是这个没有意义啊。。。谁没事私聊的时候长按消息来进入这个。。
再说 进入群消息助手本身就要关闭聊天界面的。。。
