### ISSUE TITLE
1.4.10太极提示闪退；打开已经移出“服务号消息”的企业号后无法再次打开群聊消息和服务号消息

### ISSUE THREAD

**Issue by NigelSong** [zhudongya123/WechatChatRoomHelper#41]
框架环境为无极（适配引擎版本4154），手机型号为一加6（OnePlus ONEPLUS A6000 (SDK29)），安卓10。
　　第一个问题出现在重启微信的时候，当出现微信聊天界面时太极报错，微信界面卡死，返回桌面后再次进入微信，问题消失。以下为太极阻止闪退的提示：
`太极已阻止微信闪退:
java.lang.ClassCastException: android.view.ViewGroup$MarginLayoutParams
cannot be cast to android.widget.Absolute
Layout$LayoutParams`
　　第二个问题，我把一个企业号从“服务号消息”中移出，从聊天主界面进入企业号后返回聊天界面，此时再次点击“群聊消息”或“服务号消息”，二者均无法打开，需要重启微信后才能打开。

**Comment by zhudongya123** [comment]
第一个问题将尽快修复

**Comment by zhudongya123** [comment]
群助手1.4.12（2020-09-20）：
1. 修正了布局文件错误导致的闪退问题。
下载地址： https://dxg-android.lanzous.com/ierENgs41fe


第一个问题已经修正
