### ISSUE TITLE
Play版WeChat8028失效

### ISSUE THREAD

**Issue by zyh941** [zhudongya123/WechatChatRoomHelper#59]
通过LSP安装后开启作用域，wechat app冷启动时就打不开，并且初始配置出现以下错误，请帮看看是什么回事？
[Screenshot_20221118-095908.zip](https://github.com/zhudongya123/WechatChatRoomHelper/files/10037093/Screenshot_20221118-095908.zip)

**Comment by zhudongya123** [comment]
暂时不支持play版本，如果运气好的话可以通过国内版本适配上
