### ISSUE TITLE
8.0.31无法适配

### ISSUE THREAD

**Issue by xinshikong** [zhudongya123/WechatChatRoomHelper#60]
11:22:57：kotlin.KotlinNullPointerException com.zdy.project.wechat_chatroom_helper.wechat.plugin s.classparser.WXClassParser$Adapter.getConversationW ithCacheAdapter(WXClassParser.kt:234) com.zdy.project.wechat_chatroom_helper.helper.ui.conf ig.ClassParseSyncTask.dolnBackground(ClassParseSyncT ask.kt:80) com.zdy.project.wechat_chatroom_helper.helper.ui.conf ig.ClassParseSyncTask.dolnBackground(ClassParseSyncT ask.kt:31) android.os.AsyncTask$3.call(AsyncTask.java:394) java.util.concurrent.FutureTask.run(FutureTask.java:266) android.os.AsyncTask$SerialExecutor$SerialExecutor1.run(AsyncTask.ja va:305) java.util.concurrent.ThreadPoolExecutor.runWorker(Thre adPoolExecutor.java:1167) java.util.concurrent.ThreadPoolExecutor$Worker.run(Thr eadPoolExecutor.java:641) java.lang.Thread.run(Thread.java:920) 11:22:57：遍历了40390个类，已经加载了40389个类。 11:22:55：确定微信安装包位置：/data/ app/~~YbH0VZ9j1iBVPeOhij7BwA==/ com.tencent.mm-Y8tqrFt3SS0GeSuMggjn-A==/ base.apk。 微信版本：8.0.31（2281)。 11:22:53：正在准备解析类，可能需要数分钟准备，请耐心 等待……. 11:22:53：准备开始获取配置。

**Comment by tomatoOxO** [comment]
我也是无法适配1.4.22版本

**Comment by zhudongya123** [comment]
fixed in #4a2df5f14e14bcef2c709f6021e0bf9997e2918d
