### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by 501658362** [zhudongya123/WechatChatRoomHelper#64]
模块版本1.4.24
微信版本8.0.30
手机系统miui13.0. 13
手机安装了magisk，安装了微X模块
报错信息如图
![Screenshot_2023-02-26-22-10-02-442_com zdy project wechat_chatroom_helper](https://user-images.githubusercontent.com/14038412/221415832-d38af362-17be-4c85-9acf-81ecb9061bf5.jpg)

**Comment by zhudongya123** [comment]
用之前的老版本
