### ISSUE TITLE
对于安装有存储空间隔离的用户来说，该如何使用呢？

### ISSUE THREAD

**Issue by youlan2333** [zhudongya123/WechatChatRoomHelper#68]
对于安装有存储空间隔离的用户来说，该如何使用呢？
![Screenshot_2023-07-29-22-14-23-470_com zdy project wechat_chatroom_helper](https://github.com/zhudongya123/WechatChatRoomHelper/assets/64688148/194b20c7-2b14-4d2b-8513-3ba7aeaf2ce3)

**Comment by zhudongya123** [comment]
你这个问题不是隔离导致的吧，应该就是微信新版本不支持。 可以试下微信老版本。
