### ISSUE TITLE
微信公众号助手未读计数异常

### ISSUE THREAD

**Issue by zlay0701** [zhudongya123/WechatChatroomHelper#8]
微信公众号助手，在有新的未读公众号消息的时候，会一直提示有未读消息，但是微信公众号上并没有红圈提示。

**Comment by zhudongya123** [comment]
你的意思是这个时候应该将红圈提示改为红点提示是吧

**Comment by zlay0701** [comment]
大概就是这个意思啦   ~另外 微X模块 也有群助手和公众号助手类似的功能了 不知道这俩软件的兼容性怎么样~~
